name: github pages

on:
  push:
    branches:
      - mcaptcha.io # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Check install Hugo
        run: hugo version

      - name: Install dependencies
        run: npm ci

      - name: Delete temporary directories
        run: npm run clean

      - name: Build production website
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: "mcaptcha-io-pages"

      - name: deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/mcaptcha.io' &&  github.repository == 'mCaptcha/website' }}
        run: >-
          curl --location --request POST "https://deploy.batsense.net/api/v1/update" --header 'Content-Type: application/json' --data-raw "{ \"secret\": \"${{ secrets.DEPLOY_TOKEN_MCAPTCHA_IO }}\", \"branch\": \"mcaptcha-io-pages\" }"
